### ISSUE TITLE
Please publish images for 0.18.0

### ISSUE THREAD

**Issue by niv** [moigagoo/nimage#10]
Thank you!

**Comment by moigagoo** [comment]
0.18.0 images are now available on Docker Hub: https://hub.docker.com/r/nimlang/nim/tags/

P.S. How do I subscribe for all issues and PRs in all repositories I'm admin in? Haven't seen this issue at all.

**Comment by Yardanico** [comment]
@moigagoo well you probably unwatched your own repo :P 
https://github.com/moigagoo/nimage/watchers  you're starting to watch your repo automatically after you create it

**Comment by moigagoo** [comment]
@Yardanico Thanks! Hope that helps :-)
