### ISSUE TITLE
Update to 0.19.4

### ISSUE THREAD

**Issue by ryukoposting** [moigagoo/nimage#22]
It would make my life a lot easier if the Dockerhub images were up-to-date. I'd like to get some clean CI pipelines set up on my nimble libraries, but right now it's a pain since I have to install the compiler every time my tests run.

Maybe this is something that could be done automatically when a new version of the compiler is released?

**Comment by moigagoo** [comment]
Hi! I'm really sorry for not responding to your issue quickly. Is there a way to enable email notifications for new issues in GitHub?

Anyway, I've released versions 0.19.2 and 0.19.4. I'm all for hooking to the Nim's official release events and build the images automatically, it's just that I don't know anything about the current Nim's CI pipeline.
