### ISSUE TITLE
is there a reason why alpine is on version 3.5.x?

### ISSUE THREAD

**Issue by shomodj** [moigagoo/nimage#23]

**Comment by moigagoo** [comment]
Absolutely no reason :-) I guess it was the default one?

**Comment by shomodj** [comment]
@moigagoo I can't find the code where is that defined, but I intercepted generated dockerfile and it was 3.5.x and that is really old in alpine world

**Comment by moigagoo** [comment]
It's defined here: https://github.com/moigagoo/nimage/blob/develop/flavors/slim.nim#L22

We could just replace 3.5 with latest, and that would probably do the trick.

**Comment by moigagoo** [comment]
Feel free to submit a PR.

**Comment by shomodj** [comment]
will do, give me few days

**Comment by moigagoo** [comment]
Updated base images.
