### ISSUE TITLE
Add missing releases on 1.0 and 1.2 branches?

### ISSUE THREAD

**Issue by ee7** [moigagoo/nimage#32]
This doesn't personally affect me - I'm just making an issue because I noticed that these are missing:

| Date | Version | 
| :- | - |
| 2020-07-30 | 1.0.8 |
| 2020-10-17 | 1.0.10 |
| 2020-10-17 | 1.2.8 |

See:
- https://hub.docker.com/r/nimlang/nim/tags?page=1&name=1.0
- https://hub.docker.com/r/nimlang/nim/tags?page=1&name=1.2

**Comment by moigagoo** [comment]
Added all three missing versions. Thanks!
