### ISSUE TITLE
Regular flavour: Symlink testament 

### ISSUE THREAD

**Issue by deeuu** [moigagoo/nimage#33]
Hey,

Thanks for these images!

Would it be worth creating the symbolic link `/bin/testament -> /nim/bin/testament` ? 

I'd like to use `testament` in my container out of the box.

Thanks again.

**Comment by moigagoo** [comment]
Thanks for the kind words! Sure, it's a trivial change given /nim/bin/testament is already there, let's do it.

**Comment by moigagoo** [comment]
Added the symlinks with https://github.com/moigagoo/nimage/commit/75da42950880cd1c6c6d6a8fe6aa4c0748efdd8b

**Comment by deeuu** [comment]
Awesome. Thanks again. (also love your nim work!).
