### ISSUE TITLE
nimble: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by nitely** [moigagoo/nimage#35]
Nim 1.0.10, and 1.2.8 throw this error, see https://github.com/nitely/nim-regex/runs/1397082756

I tried these version on my machine with choosenim, they work well. I didn't try the docker images, though.

Any idea what is this about? The other versions I'm testing work just fine, see https://github.com/nitely/nim-regex/blob/master/.github/workflows/ci.yml#L15

**Comment by moigagoo** [comment]
The images for these versions are outdated, I need to rebuild them. I'll try to do that today.

**Comment by moigagoo** [comment]
@nitely I've rebuilt the images. Please try running your code again and see it the issue is fixed.

**Comment by nitely** [comment]
It works! Thanks
