### ISSUE TITLE
Provide images for non x86_64 architectures

### ISSUE THREAD

**Issue by benob** [moigagoo/nimage#36]
I am thinking of Raspberry pi 4 which is aarch64

**Comment by moigagoo** [comment]
Sounds like a very much doable thing. However, I'm not familiar with Raspberry Pi, don't even know what OS it has. So, if you're in the loop, feel free to send a PR.

**Comment by benob** [comment]
I haven't compiled the hole set of images, but I was able to get nim:alpine to work out of the box (host OS is ubuntu).
- Is it possible to cross-compile using an emulator such as qemu to cross-compile from an x86_64 host ?
- Would you be interested for me to compile the images and upload them to my docker hub account?

**Comment by benob** [comment]
For reference I have started uploading arm64 images to https://hub.docker.com/r/benob/nim

**Comment by moigagoo** [comment]
Duplicates #40
