### ISSUE TITLE
Source code is fetched over http

### ISSUE THREAD

**Issue by wezm** [moigagoo/nimage#37]
To help prevent the possibility of tampering I suggest downloading over https E.g.

https://github.com/moigagoo/nimage/blob/d0d5a0f1f1032d95ec693f632ee763dae8a00645/flavors/slim.nim#L27
https://github.com/moigagoo/nimage/blob/d0d5a0f1f1032d95ec693f632ee763dae8a00645/flavors/slim.nim#L11

**Comment by moigagoo** [comment]
Feel free to submit a PR.
