### ISSUE TITLE
No nimble in slim variant ?

### ISSUE THREAD

**Issue by waghanza** [moigagoo/nimage#59]
Hi @moigagoo @ire4ever1190,

I can see in slim variant (`nimlang/nim:2.0.0-slim` in my case)
https://github.com/the-benchmarker/web-frameworks/actions/runs/6810554512/job/18519081144?pr=6913#step:7:82

That there is no `nimble`.

In **alpine** and **debian** based image, `nimble` is there.

Is it on purpose ?

**Comment by moigagoo** [comment]
Yes that's on purpose. They are slim because they only have Nim compiler. Use regular flavor for the full package.

I don't quite understand what you mean by Debian based images. My images are based on Ubuntu and Alpine.

**Comment by waghanza** [comment]
Sorry ubuntu;

I use to have slimmer image when dealing with slim variant, less packages installed ...
