### ISSUE TITLE
Update for 0.15.0

### ISSUE THREAD

**Issue by johnscillieri** [moigagoo/nimage#6]
Can you provide new targets for v0.15.0? If you're busy need a pull request let me know.

**Comment by guitmz** [comment]
Sure, I'll update asap.

**Comment by guitmz** [comment]
I guess this PR should close this https://github.com/moigagoo/nimage/pull/7, if anyone could double check it I would appreciate as I'm very sleepy at the moment :)

**Comment by johnscillieri** [comment]
tested with nimlang/nim:0.15.0-alpine, looks good.
