### ISSUE TITLE
Onbuild: Replace `build` with `install`

### ISSUE THREAD

**Issue by moigagoo** [moigagoo/nimage#8]
When Nim 0.16.1 is released with Nimble 0.8.4, the bug that doesn't let you install binary packages will be fixed. When this happens, we should replace `build` with `install` for onbuild images.

**Comment by guitmz** [comment]
agreed, was hoping for that :)

**Comment by guitmz** [comment]
very nice, I was going to to it now myself but you were faster :) closing this one!

**Comment by moigagoo** [comment]
I was waiting on Travis CI to finish the build before closing this issue :-) But it's very unlikely my change will break anything, so it's OK.

**Comment by moigagoo** [comment]
Turns out this was not that good of an idea. I couldn't make my project run properly after this change.

**Comment by moigagoo** [comment]
Reverted to `build`.

**Comment by guitmz** [comment]
@moigagoo ok, I will test it locally later to check the effects of this change
